################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[de]
languageName = "Deutsch"
languageCode = "de-de"
contentDir = "content/german"
weight = 2