############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Prints"
url = "/prints"
weight = 2

#[[main]]
#name = "Catalogue"
#url = "/catalogue"
#weight = 3

#[[main]]
#weight = 4
#name = "Catalogue"
#url = "/catalogue"

#[[main]]
#parent = "Catalogue"
#name = "16inch Balloons"
#url = "/catalogue/types/16"

#[[main]]
#parent = "Catalogue"
#name = "18inch Balloons"
#url = "/catalogue/types/18"

#[[main]]
#parent = "Catalogue"
#name = "24inch Balloons"
#url = "/catalogue/types/24"

#[[main]]
#parent = "Catalogue"
#name = "32inch Balloons"
#url = "/catalogue/types/32"

#[[main]]
#parent = "Catalogue"
#name = "36inch Balloons"
#url = "/catalogue/types/36"

[[main]]
name = "About"
url = "/about"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2
